server:
  port: 8082

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:mariadb://lecturedb:3306/lecture_db 
    # 컨테이너 이름 lecturedb 로 입력 (원래 IP를 입력하지만, 재부팅 시 변경될 수 있는 가능성 제거)
    username: manager
    password: SqlDba-1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 서비스 간 통신 설정
service:
  user-service:
    url: http://user-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html